# Generated by Django 5.2.11 on 2026-03-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(default=0)),
                ('transports', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to='core.userdetails')),
            ],
            options={
                'verbose_name': 'Passkey Credential',
                'verbose_name_plural': 'Passkey Credentials',
                'db_table': 'passkey_credentials',
            },
        ),
    ]
